mysql: &mysql
  adapter: mysql2
  reconnect: true
  pool: 5
  strict: false
  encoding: ujis

production:
  <<: *mysql
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *mysql
  database: fifteen
  host: localhost
  username: root
  password:

test:
  <<: *mysql
  database: fifteen_test
  host: localhost
  username: root
  password:

