production:
  adapter: mysql2
  url: <%= ENV['DATABASE_URL'] %>

mysql: &mysql
  adapter: mysql2
  reconnect: false
  pool: 5
  strict: false
  encoding: ujis

development:
  <<: *mysql
  database: fifteen
  host: localhost
  username: root
  password:

test:
  <<: *mysql
  database: fifteen_test
  host: localhost
  username: root
  password:

